### ISSUE TITLE
想和大佬交个朋友

### ISSUE THREAD

**Issue by sun0225SUN** [xsro/xsro#1]
打扰了哈，本来想在你网站上留言来着，然后没找到留言板/评论区，想着给你发邮件或者twitter你应该也不经常看，所以就开了个issues
是这样的，我也是学生。现在正在读大三，想跨考计科，比较想考南京的学校。但我对南京这块的院校不是很熟悉，看着你GitHub的位置写的是江苏南京，所以想认识一下大佬。🦸

**Comment by xsro** [comment]
欢迎呀，我是南邮的学生，不过我不是计算机相关专业，编程只是爱好。
将来我要去双鸭山大学读控制科学。

据我所知南邮的计科性价比还是很高的，与很多大厂有合作，水平还是很强的。
华为中兴都会来招聘。
当然在南京的话如果能考（保）上南大，东南更好哈，南邮应该和南航，南理工，河海实力差不多。

PS. 据说南邮计算机竞争也有些激烈，现在很多理工类学校也有很多计算机科学相关专业。

加油，欢迎来南邮玩。我QQ 2281536971

**Comment by sun0225SUN** [comment]
好哒
